
language: cpp
sudo: required
services:
  - docker
before_install:
  - docker build -t starflow_analytics .
script:
  - docker run starflow_analytics /bin/sh -c "/root/starflow_analytics/build/test_runner"